
version: 2

models:
  - name: source_overlap
    description: 'Overlap between sources on each download'
    columns: 
      - name: source
        description: 'The data download source'
        data_tests:
          - not_null
          - unique

  - name: repeats
    description: 'All unique stock tickers observed by source and the number of times they recur'
    columns:
      - name: source
        description: 'Data source'
        tests:
          - not_null
      - name: symbol
        description: 'The stock ticker'
        tests: 
          - not_null

  - name: reliability
    description: 'The proportion of total attempted downloads successfully executed for each data source'
    columns:
      - name: source
        description: 'Data source'
        tests:
          - not_null
