
version: 2

models:
  - name: downloads
    description: 'Gainer download date/time information'
    columns: 
      - name: date_time
        description: 'The combined date and timestamp, primary key'
        data_tests:
          - not_null
          - unique

  - name: sources
    description: 'Gainer data sources'
    columns:
      - name: source
        description: 'The name of the download source'
        data_tests:
          - not_null
          - unique

  - name: gainers
    description: 'Stock tickers found in the gainers data'
    columns: 
      - name: symbol
        description: 'The stock ticker'
        data_tests:
          - not_null
          - unique

  - name: gainer_details
    description: 'Main gainers table'
    columns:
      - name: date_time
        description: 'FK: YYYYMMDD_HHMM matching value in Downloads table'
        data_tests:
          - not_null
          - relationships:
              to: ref('downloads')
              field: date_time
      - name: source
        description: 'FK: data source matching value in Sources table'
        data_tests:
          - not_null
          - relationships:
              to: ref('sources')
              field: source
      - name: symbol
        description: 'FK: stock ticker matching value in Gainers table'
        data_tests:
          - not_null
          - relationships:
              to: ref('gainers')
              field: symbol
      - name: price
        description: 'Price of gainer on given day/time'
        data_tests:
          - not_null
      - name: price_change
        description: 'Change in price of gainer on given day/time'
        data_tests:
          - not_null
      - name: price_percent_change
        description: 'Percent change in price of gainer on given day/time'
        data_tests:
          - not_null
